import type { HomeCopy } from "./types";

/**
 * Copy inglés de la HOME (`/en`).
 *
 * La estructura es idéntica a la ruta española: los mismos componentes, las
 * mismas secciones y los mismos identificadores de fragmento. Cambia el idioma
 * y la entidad que firma la página: `/en` habla desde INPLUX LLC, la sociedad
 * de Miami que presta los servicios en el exterior, con el equipo de ingeniería
 * de INPLUX S.A.S. en Medellín.
 *
 * Los enlaces a rutas que solo existen en español van marcados con `hrefLang`
 * para no prometer una traducción que no publicamos.
 */

const spanishRoute = (label: string, href: string) => ({
  label,
  href,
  hrefLang: "es",
});

export const homeCopyEn: HomeCopy = {
  locale: "en_US",
  htmlLang: "en-US",

  header: {
    skipToContent: "Skip to content",
    brandLabel: "INPLUX, go to the start of the page",
    navigationLabel: "Main navigation",
    mobileNavigationLabel: "Mobile navigation",
    mobileMenuLabel: "Explore INPLUX",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    contactCta: "Start a project",
    contactCtaMobile: "Start a project",
    menuNote: "You don't need a defined scope to begin.",
    navigation: [
      { label: "The factory", href: "#fabrica-en-vivo" },
      { label: "What we build", href: "#que-construimos" },
      { label: "Where we work", href: "#donde-trabajamos" },
      { label: "How we work", href: "#como-trabajamos" },
      { label: "Press", href: "#prensa" },
    ],
    languageSwitch: { label: "Español", href: "/", hrefLang: "es" },
  },

  footer: {
    heading: "Footer",
    tagline: "A custom software factory for companies and public institutions.",
    groups: [
      {
        label: "Explore",
        ariaLabel: "Explore",
        items: [
          { label: "The factory", href: "#fabrica-en-vivo" },
          { label: "What we build", href: "#que-construimos" },
          { label: "Where we work", href: "#donde-trabajamos" },
          { label: "How we work", href: "#como-trabajamos" },
          { label: "Press", href: "#prensa" },
        ],
      },
      {
        label: "Products",
        ariaLabel: "Documented products",
        items: [
          spanishRoute("Tribai", "/trabajo/tribai"),
          spanishRoute("Gobia", "/trabajo/gobia"),
          spanishRoute("Kelsen", "/trabajo/kelsen"),
          spanishRoute("Laudos", "/trabajo/laudos"),
        ],
      },
      {
        label: "Capabilities",
        ariaLabel: "Capabilities",
        items: [
          spanishRoute("Digital product", "/capacidades#producto"),
          spanishRoute("Modernization", "/capacidades#modernizacion"),
          spanishRoute("Applied AI", "/capacidades#ia"),
          spanishRoute("Public services", "/capacidades#sector-publico"),
        ],
      },
    ],
    contactLabel: "Contact",
    contactAriaLabel: "Contact",
    contactCta: "Start a project",
    email: "gerencia@inplux.co",
    linkedInLabel: "LinkedIn",
    locations: ["Miami, Florida · United States", "Medellín · Colombia"],
    languageNote: "Product and company pages are published in Spanish.",
    copyright: "INPLUX LLC · INPLUX S.A.S.",
    closingLine: "Software with judgment and human direction.",
  },

  contactDialog: {
    eyebrow: "Let's start with the problem",
    titleLead: "What do you need to ",
    titleEmphasis: "build",
    titleTail: "?",
    description:
      "Tell us what should change. You don't need to arrive with requirements or a defined scope.",
    closeLabel: "Close contact form",
  },

  contactForm: {
    dialogLabel: "Contact form in dialog",
    sectionLabel: "Contact form on the page",
    nameLabel: "Name",
    organizationLabel: "Company or institution",
    organizationOptional: "optional",
    needLabel: "What kind of need do you have?",
    needOptions: [
      "Launch a digital product",
      "Improve an operation",
      "Automate work and knowledge",
      "I'm not sure yet",
    ],
    needDefault: "I'm not sure yet",
    challengeLabel: "What problem do you need to solve?",
    challengePlaceholder:
      "Tell us the problem, who lives with it and what should change.",
    note: "We'll prepare a draft in your email application. This page does not send or store the data.",
    submit: "Open a draft in my email",
    preparedNote:
      "The draft is ready. If your email application did not open, you can copy the message and send it through whichever channel you prefer.",
    copyAction: "Copy the prepared message",
    copySuccess: "Message copied. You can paste it wherever you prefer.",
    copyFailure:
      "We couldn't copy it automatically. The message is selected below.",
    manualCopyLabel: "Message prepared for manual copying",
    mailSubject: "New software challenge · {organization}",
    mailFieldName: "Name",
    mailFieldOrganization: "Company or institution",
    mailFieldOrganizationEmpty: "Not provided",
    mailFieldNeed: "Type of need",
    mailChallengeHeading: "Challenge:",
    mailTo: "To",
    mailSubjectLabel: "Subject",
  },

  hero: {
    eyebrow: "CUSTOM SOFTWARE FACTORY · MIAMI, FLORIDA",
    titleLines: ["From a real problem", "to software in production."],
    leadSentences: [
      "INPLUX designs, builds and evolves digital products for companies and public institutions.",
      "AI accelerates the work. Expert people direct and validate the critical decisions.",
    ],
    primaryCta: "Start a project",
    secondaryCta: "See real work",
    statement: "SOFTWARE STARTS WITH THE PROBLEM",
    signalAriaLabel: "Interactive visual of the flow of a software factory",
    signalMeta: [
      "INPUT / CONTEXT",
      "MOVE THE CURSOR TO EXPLORE",
      "OUTPUT / PRODUCT IN OPERATION",
    ],
    signalStages: [
      { number: "01", title: "REAL PROBLEM", detail: "PEOPLE + CONTEXT" },
      { number: "02", title: "BUILD", detail: "DESIGN + ENGINEERING" },
      { number: "03", title: "IN PRODUCTION", detail: "MEASURE + EVOLVE" },
    ],
    signalAxis: "BUILD / 01",
  },

  experienceRail: {
    ribbonAriaLabel: "Products with confirmed public attribution to INPLUX",
    ribbonEyebrow: "ATTRIBUTABLE WORK / PRODUCTS",
    ribbonTitle: "Work we can actually claim.",
    directoryEyebrow: "EVIDENCE / ATTRIBUTION",
    directoryName: "Directory",
    directoryDetail: " documented profiles",
    logoWallAriaLabel: "Organizations INPLUX has worked with.",
    statementEyebrow: "REAL RELATIONSHIPS",
    statementTitle: "EXPERIENCE AND ALLIANCES",
    statementHint: "SWIPE TO SEE 10 →",
    relationExperience: "Experience",
    relationPartner: "Partner",
    clientNotes: {
      "/brand/clients/parque-arvi.png": "Tourism, territory and sustainability",
      "/brand/clients/think-it.png": "Technology partner",
      "/brand/clients/experience-03.png": "Inter-institutional services",
      "/brand/clients/politecnico-jaime-isaza.png": "Public higher education",
      "/brand/clients/experience-04.png": "Territorial cooperation",
      "/brand/clients/experience-05.png": "Business operations",
      "/brand/clients/experience-06-transparent.png": "Urban development",
      "/brand/clients/experience-07.png": "Technology for public management",
      "/brand/clients/municipio-cisneros.png": "Territorial public management",
      "/brand/clients/experience-08.png": "Territorial public management",
    },
    productCategories: {
      gobia: "Public management",
      laudos: "Arbitration",
    },
    productStatuses: {
      gobia: "Active pilot",
      laudos: "Open beta",
    },
  },

  factoryScrolly: {
    disclosure: "Interactive demo · illustrative data",
    sceneDisclosure: "Demo / 04 stages",
    eyebrow: "01 / THE FACTORY, LIVE",
    titleLead: "Software built to ",
    titleEmphasis: "evolve.",
    lead: "We don't assemble isolated screens. We build a system where context, product and engineering move together until useful software is running in production.",
    timelineAriaLabel: "Stages of the factory",
    introStatus: "Introduction to the factory",
    stageStatus: "Stage {index} of {total}: {label}. {title}.",
    steps: [
      {
        index: "01",
        label: "YOUR CHALLENGE",
        title: "Understand",
        copy: "We observe the context, listen to the people involved and make visible the problem that is genuinely worth solving.",
        signals: ["PEOPLE / CONTEXT", "RULES / FRICTION"],
      },
      {
        index: "02",
        label: "THE PRODUCT",
        title: "Give it shape",
        copy: "We turn what we learned into priorities, flows and an experience that can be tested before it scales.",
        signals: ["FLOWS / DECISIONS", "INTERFACE / PROTOTYPE"],
      },
      {
        index: "03",
        label: "THE FACTORY",
        title: "Build",
        copy: "Design, engineering and applied intelligence work as a single system, with human review at every critical point.",
        signals: ["DESIGN / ENGINEERING", "AI / HUMAN REVIEW"],
      },
      {
        index: "04",
        label: "IN PRODUCTION",
        title: "Evolve",
        copy: "We release a useful version, watch how it behaves and decide with you what to improve based on real evidence.",
        signals: ["DATA / LEARNING", "OPERATION / EVOLUTION"],
      },
    ],
  },

  solutions: {
    eyebrow: "02 / WHAT WE BUILD",
    titleLead: "Software for what your organization needs to ",
    titleEmphasis: "make possible.",
    tabsAriaLabel: "Types of project",
    disclosure: "INTERACTIVE DEMO · ILLUSTRATIVE DATA",
    projectPrefix: "PROJECT",
    factoryLabel: "INPLUX FACTORY",
    toggleTitle: "Switch between the application and the API",
    requestPaneLabel: "API request",
    responsePaneLabel: "API response",
    copyAction: "COPY",
    copyDone: "COPIED",
    copyFailed: "COULD NOT COPY",
    copyRequestLabel: "Copy the request for project {project}",
    copyResponseLabel: "Copy the response for project {project}",
    responseNotRun: "NOT RUN",
    responseRunning: "EXECUTING",
    responseIdleHint: "Run the request to inspect the response.",
    responseRunningHint: "Validating contract and permissions…",
    runRequest: "RUN REQUEST",
    runAgain: "RUN AGAIN",
    running: "RUNNING…",
    sandboxReady: "SANDBOX READY",
    validatingContract: "VALIDATING CONTRACT",
    responseReady: "RESPONSE READY",
    workbenchLabel: "API WORKBENCH",
    projectFieldLabel: "PROJECT",
    ownerFieldLabel: "OWNER",
    stateFieldLabel: "STATE",
    projectIdFieldLabel: "PROJECT ID",
    environmentFieldLabel: "ENVIRONMENT",
    updatedFieldLabel: "UPDATED",
    appNavigation: ["SUMMARY", "ACTIVITY", "EVIDENCE"],
    ownerAriaLabel: "Owner: {owner}",
    recentActivityLabel: "RECENT ACTIVITY",
    outcomeLabel: "OUTCOME",
    items: [
      {
        number: "01",
        title: "Launch a digital product",
        copy: "We turn an opportunity into a first useful version, ready to learn and grow.",
        status: "PRODUCT DISCOVERY",
        outcome: "First version ready to validate",
        modules: ["Context", "Experience", "Product", "Delivery"],
        image: "/brand/home/solution-product.webp",
        imagePosition: "50% 50%",
        project: {
          id: "PRJ-0718",
          name: "Pilot orbit",
          owner: "Laura M.",
          ownerInitials: "LM",
          state: "Ready to validate",
          environment: "PILOT",
          updated: "12 min ago",
        },
        ui: {
          kind: "release",
          eyebrow: "PRODUCT RELEASE / 01",
          value: "V1.0",
          description: "First version prepared for validation.",
          metrics: [
            ["PILOT USERS", "48"],
            ["KEY FLOWS", "06"],
            ["COVERAGE", "82%"],
            ["RISK", "LOW"],
          ],
          progress: 82,
          progressLabel: "Validation coverage",
          activity: [
            ["Onboarding", "VALIDATED"],
            ["Main flow", "READY"],
          ],
          artifact: {
            stages: ["DISCOVERY", "PROTOTYPE", "PILOT", "RELEASE"],
            cohortLabel: "PILOT COHORT",
            cohortValue: "48 PEOPLE · 06 FLOWS",
          },
        },
        api: {
          method: "POST",
          endpoint: "/v1/projects/PRJ-0718/releases",
          action: "publish_pilot_release",
          httpStatus: "201 CREATED",
          latency: "86 ms",
        },
      },
      {
        number: "02",
        title: "Modernize an operation",
        copy: "We connect people, processes, rules and data around the way the work actually happens.",
        status: "OPERATION DESIGN",
        outcome: "A connected, traceable operation",
        modules: ["People", "Processes", "Rules", "Data"],
        image: "/brand/home/solution-operation.webp",
        imagePosition: "50% 52%",
        project: {
          id: "OPS-1842",
          name: "Case flow",
          owner: "Santiago R.",
          ownerInitials: "SR",
          state: "Running",
          environment: "PRODUCTION",
          updated: "4 min ago",
        },
        ui: {
          kind: "operation",
          eyebrow: "CASE FLOW / 1842",
          value: "12m",
          description: "Median time to resolve a case.",
          metrics: [
            ["ACTIVE CASES", "186"],
            ["STEPS", "04"],
            ["SLA", "94%"],
            ["REWORK", "−31%"],
          ],
          progress: 74,
          progressLabel: "Flow completed",
          activity: [
            ["Rule validation", "PASS"],
            ["Automatic assignment", "DONE"],
          ],
          artifact: {
            queues: [
              ["INTAKE", "186"],
              ["VALIDATION", "42"],
              ["REVIEW", "18"],
              ["RESOLVED", "126"],
            ],
          },
        },
        api: {
          method: "POST",
          endpoint: "/v1/projects/OPS-1842/cases/1842/advance",
          action: "advance_to_human_review",
          httpStatus: "200 OK",
          latency: "112 ms",
        },
      },
      {
        number: "03",
        title: "Activate knowledge with AI",
        copy: "We turn repetitive tasks and scattered knowledge into clear flows, under human control.",
        status: "KNOWLEDGE SYSTEM",
        outcome: "Knowledge available at the moment of deciding",
        modules: ["Sources", "Criteria", "Flows", "Review"],
        image: "/brand/home/solution-knowledge.webp",
        imagePosition: "50% 45%",
        project: {
          id: "KNO-0031",
          name: "Assisted judgment",
          owner: "María P.",
          ownerInitials: "MP",
          state: "Review approved",
          environment: "CONTROLLED",
          updated: "7 min ago",
        },
        ui: {
          kind: "knowledge",
          eyebrow: "KNOWLEDGE QUERY / 031",
          value: "94%",
          description: "Confidence of the answer, with evidence.",
          metrics: [
            ["SOURCES", "04"],
            ["CITATIONS", "07"],
            ["REVIEW", "HUMAN"],
            ["QUEUE", "00"],
          ],
          progress: 94,
          progressLabel: "Verified confidence",
          activity: [
            ["Internal policy", "CITED"],
            ["Expert judgment", "APPROVED"],
          ],
          artifact: {
            statement:
              "The decision applies when verifiable evidence exists and an accountable person confirms the criterion.",
            chips: ["SOURCE 01", "SOURCE 02", "EXPERT JUDGMENT"],
            chipVerdict: "REVIEWED",
          },
        },
        api: {
          method: "POST",
          endpoint: "/v1/projects/KNO-0031/knowledge/query",
          action: "answer_with_verified_sources",
          httpStatus: "200 OK",
          latency: "148 ms",
        },
      },
      {
        number: "04",
        title: "Evolve a public service",
        copy: "We design clear experiences for citizens and internal teams, tracked end to end.",
        status: "PUBLIC SERVICE",
        outcome: "A visible, connected and measurable service",
        modules: ["Citizens", "Procedure", "Tracking", "Control"],
        image: "/brand/home/solution-public-service.webp",
        imagePosition: "50% 52%",
        project: {
          id: "GOV-0184",
          name: "Connected procedure",
          owner: "Ana C.",
          ownerInitials: "AC",
          state: "In technical review",
          environment: "SERVICE",
          updated: "9 min ago",
        },
        ui: {
          kind: "service",
          eyebrow: "PROCEDURE / 2026-0184",
          value: "03 / 04",
          description: "Current stage, visible to citizens and to the team.",
          metrics: [
            ["REQUESTS", "284"],
            ["MEDIAN TIME", "2.4D"],
            ["TRACEABILITY", "100%"],
            ["ALERTS", "02"],
          ],
          progress: 75,
          progressLabel: "Procedure progress",
          activity: [
            ["Document received", "VERIFIED"],
            ["Technical review", "IN PROGRESS"],
          ],
          artifact: {
            steps: [
              ["01", "REQUEST", "DONE"],
              ["02", "DOCUMENTS", "DONE"],
              ["03", "TECHNICAL REVIEW", "ACTIVE"],
              ["04", "ANSWER", "NEXT"],
            ],
          },
        },
        api: {
          method: "GET",
          endpoint: "/v1/projects/GOV-0184/procedures/2026-0184",
          action: "read_procedure_status",
          httpStatus: "200 OK",
          latency: "96 ms",
        },
      },
    ],
  },

  apiChapter: {
    eyebrow: "03 / INTEGRATION",
    titleLead: "Ready to integrate.",
    titleTail: "Built to ",
    titleEmphasis: "evolve.",
    lead: "We build software that talks to what your organization already uses and leaves a clear foundation for whatever comes next.",
    capabilities: [
      [
        "Clear interfaces and APIs",
        "Every integration has a contract that can be understood and verified.",
      ],
      [
        "Security by design",
        "Identity, permissions and traceability are defined from the start.",
      ],
      [
        "Observable integrations",
        "We know what happened, when and why, without depending on black boxes.",
      ],
      [
        "Living documentation",
        "The product and its documentation evolve as a single piece.",
      ],
    ],
    primaryCta: "Let's talk about your architecture",
    secondaryCta: "See the factory",
    demoAriaLabel: "Demo for creating a project in INPLUX Factory",
    demoDisclosure: "INTERACTIVE DEMO · ILLUSTRATIVE DATA",
    createProjectComment: "// CREATE PROJECT",
    environmentLabel: "ENV / SANDBOX",
    regionLabel: "REGION / LATAM-01",
    copyEndpoint: "Copy endpoint",
    copiedEndpoint: "Endpoint copied",
    copiedTitle: "Copied",
    copyEndpointAnnouncement: "Endpoint copied to the clipboard.",
    copyEndpointFailure: "The endpoint could not be copied.",
    sandboxReady: "SANDBOX READY",
    creatingProject: "CREATING PROJECT…",
    projectCreated: "PROJECT CREATED",
    runRequest: "RUN REQUEST",
    running: "RUNNING",
    runAgain: "RUN AGAIN",
    responseReadyLabel: "READY",
    responseCreatedLabel: "201 / CREATED",
    responseFields: [
      ["PROJECT", "IX-0718"],
      ["NEXT GATE", "CONTEXT / 01"],
      ["TRACE", "ENABLED"],
    ],
    openInFactoryRun: "OPEN IX-0718 IN FACTORY RUN",
  },

  sectors: {
    eyebrow: "04 / WHERE WE WORK",
    title: "Two contexts. One product standard.",
    publicEyebrow: "PUBLIC SECTOR / 01",
    publicTitle: "Services that hold the collective together.",
    publicCopy:
      "We digitize service, information and follow-up so the operation becomes clearer, more connected and traceable.",
    publicItems: [
      "Service and procedures",
      "Management and follow-up",
      "Data for deciding",
    ],
    publicCta: "Let's talk about a public challenge",
    privateEyebrow: "PRIVATE SECTOR / 02",
    privateTitle: "Products that move the business.",
    privateCopy:
      "We build products and internal tools that turn processes, knowledge and data into an operation that can grow.",
    privateItems: [
      "Digital products",
      "Internal operations",
      "Automation with control",
    ],
    privateCta: "Let's talk about a private challenge",
  },

  build: {
    eyebrow: "05 / HOW WE WORK",
    title: "A factory designed to deliver.",
    lead: "Technology changes fast. Our way of working is designed to learn without losing clarity, accountability or control.",
    deliveryChecks: [
      [
        "Problem and outcome first",
        "We align purpose, people and evidence before defining the scope.",
      ],
      [
        "Design and engineering together",
        "A single working table reduces hand-offs and late decisions.",
      ],
      [
        "Frequent demonstrations",
        "You see software running and decide with something concrete in front of you.",
      ],
      [
        "Intelligence under supervision",
        "AI accelerates the work; human judgment keeps the direction.",
      ],
      [
        "Measurement in production",
        "Every version produces signals for deciding what is worth evolving.",
      ],
    ],
    primaryCta: "Start a project",
    secondaryCta: "See the factory",
    capabilitiesEyebrow: "06 / MADE TO MOVE",
    capabilitiesTitle: "Delivery pace, without losing judgment or control.",
    capabilities: [
      [
        "01",
        "Purpose before scope",
        "We start from the problem and the expected outcome, not from a closed list of screens.",
      ],
      [
        "02",
        "A single working table",
        "Context, design and engineering decide together to reduce loss of information.",
      ],
      [
        "03",
        "Intelligence under supervision",
        "AI systems accelerate research, code and testing; the decisions remain under human direction.",
      ],
      [
        "04",
        "Evidence to evolve",
        "Every version in use produces signals that guide the next product decision.",
      ],
    ],
    factoryRun: {
      regionAriaLabel:
        "INPLUX Factory Run. Select a phase to inspect its execution.",
      demoFlag: "INTERACTIVE DEMO",
      demoFlagDetail: "ILLUSTRATIVE DATA",
      runLabel: "RUN IX-0718",
      runOwnerAriaLabel: "Owner Cristian Espinal",
      railAriaLabel: "Factory Run navigation",
      projectLabel: "PROJECT",
      projectName: "Permit portal",
      projectMeta: "IX-0718 · RUNNING",
      phasesLabel: "DELIVERY PHASES",
      phaseTabsAriaLabel: "Phases of the factory",
      runActive: "RUN ACTIVE",
      breadcrumbProject: "Project",
      breadcrumbPhase: "Phase",
      scrollableDetailAriaLabel: "Scrollable detail of the {phase} phase",
      inspectorAriaLabel: "Inspector for {phase}",
      phasePrefix: "INPLUX FACTORY · PHASE",
      ownerLabel: "OWNER",
      gateProgressAriaLabel: "Progress of the {gate} gate",
      gateLabel: "GATE",
      boardPriorities: "3 VISIBLE PRIORITIES",
      propertiesTitle: "Properties",
      gateFieldLabel: "Gate",
      milestoneFieldLabel: "Milestone",
      updatedFieldLabel: "Updated",
      activityTitle: "Activity",
      activityCount: "2 RECENT",
      authorityLabel: "DIRECTION",
      authorityNote: "AI proposes and executes. A person keeps the decision.",
      scrollCue: "SWIPE FOR MORE DETAIL",
      runApiLabel: "RUN API",
      syncedLabel: "DATA SYNCED",
      announcement: "Active phase: {phase}. Status {status}.",
      phases: [
        {
          code: "01",
          id: "CTX-07",
          title: "Context",
          status: "ALIGNED",
          statusTone: "approved",
          summary:
            "We bring conversations, constraints and evidence together so the outcome has a shared definition.",
          progress: 84,
          boardLabel: "Context evidence",
          boardNote: "4 items · 1 needs a decision",
          owner: "Cristian Espinal",
          ownerInitials: "CE",
          gate: "Shared outcome",
          milestone: "Definition / Jul 19",
          updated: "09:12 COT",
          metrics: [
            { label: "Actors", value: "12", detail: "mapped" },
            { label: "Rules", value: "18", detail: "traced" },
            { label: "Friction", value: "06", detail: "prioritized" },
          ],
          workItems: [
            {
              id: "CTX-12",
              type: "BRIEF",
              title: "The outcome that must change",
              detail:
                "Cut the intake of a complete request from 11 days to 4.",
              state: "approved",
              stateLabel: "Approved",
              owner: "CE",
            },
            {
              id: "CTX-15",
              type: "PEOPLE",
              title: "Map of actors and authority",
              detail:
                "Citizens, technical review and legal approval, connected.",
              state: "approved",
              stateLabel: "Traced",
              owner: "ME",
            },
            {
              id: "CTX-18",
              type: "FRICTION",
              title: "Identity validation",
              detail: "Define an exception for documents that read incompletely.",
              state: "review",
              stateLabel: "Review",
              owner: "LP",
            },
            {
              id: "CTX-21",
              type: "EVIDENCE",
              title: "Success threshold",
              detail:
                "80% complete the flow unassisted on the first session.",
              state: "ready",
              stateLabel: "Ready",
              owner: "AG",
            },
          ],
          activity: [
            {
              initials: "ME",
              actor: "María E.",
              action: "connected 3 rules to the validation flow",
              time: "08:58",
              state: "approved",
            },
            {
              initials: "LP",
              actor: "Laura P.",
              action: "requested legal judgment on CTX-18",
              time: "08:41",
              state: "review",
            },
            {
              initials: "CE",
              actor: "Cristian E.",
              action: "set the outcome and its threshold",
              time: "Yesterday",
              state: "ready",
            },
          ],
          command: "inplux context lock --outcome service-adoption",
        },
        {
          code: "02",
          id: "PRD-18",
          title: "Product",
          status: "VALIDATING",
          statusTone: "active",
          summary:
            "We make the solution visible before building it: flows, decisions and prototypes people can try.",
          progress: 68,
          boardLabel: "Product plan",
          boardNote: "4 stories · session 03 under way",
          owner: "Ana Gómez",
          ownerInitials: "AG",
          gate: "Understandable flow",
          milestone: "Prototype / Jul 22",
          updated: "11:46 COT",
          metrics: [
            { label: "Flows", value: "04", detail: "modelled" },
            { label: "Tests", value: "09", detail: "completed" },
            { label: "Clarity", value: "8.7", detail: "out of 10" },
          ],
          workItems: [
            {
              id: "PRD-31",
              type: "FLOW",
              title: "File a request",
              detail: "Intake, validation and confirmation in a single journey.",
              state: "approved",
              stateLabel: "Validated",
              owner: "AG",
            },
            {
              id: "PRD-34",
              type: "PROTOTYPE",
              title: "Tracking inbox",
              detail: "Status, next steps and evidence visible for every case.",
              state: "active",
              stateLabel: "Testing",
              owner: "SM",
            },
            {
              id: "PRD-37",
              type: "DECISION",
              title: "Recovering a request",
              detail:
                "Two alternatives still open after testing with 5 people.",
              state: "review",
              stateLabel: "Decide",
              owner: "CE",
            },
            {
              id: "PRD-40",
              type: "CONTENT",
              title: "Validation messages",
              detail: "Plain language reviewed; accessibility check pending.",
              state: "queued",
              stateLabel: "Queued",
              owner: "LP",
            },
          ],
          activity: [
            {
              initials: "SM",
              actor: "Santiago M.",
              action: "published prototype 0.8",
              time: "11:46",
              state: "active",
            },
            {
              initials: "AG",
              actor: "Ana G.",
              action: "closed 3 usability findings",
              time: "10:22",
              state: "approved",
            },
            {
              initials: "CE",
              actor: "Cristian E.",
              action: "scheduled the decision for PRD-37",
              time: "09:54",
              state: "review",
            },
          ],
          command: "inplux prototype test --flow citizen-onboarding",
        },
        {
          code: "03",
          id: "BLD-42",
          title: "Build",
          status: "ASSEMBLING",
          statusTone: "active",
          summary:
            "Design and engineering work on the same system, with specialized assistants and human review at every gate.",
          progress: 57,
          boardLabel: "Changes in integration",
          boardNote: "3 changes · CI running",
          owner: "Mateo Ríos",
          ownerInitials: "MR",
          gate: "Verifiable quality",
          milestone: "Candidate / Jul 25",
          updated: "14:08 COT",
          metrics: [
            { label: "Changes", value: "38", detail: "integrated" },
            { label: "Coverage", value: "92%", detail: "critical paths" },
            { label: "Assistants", value: "04", detail: "supervised" },
          ],
          workItems: [
            {
              id: "PR-184",
              type: "MERGE REQUEST",
              title: "feat/intake-validation",
              detail: "17 files · +426 −118 · commit a91e2f7",
              state: "active",
              stateLabel: "CI 7/9",
              owner: "MR",
            },
            {
              id: "BLD-46",
              type: "CONTRACT",
              title: "Filing schema v3",
              detail:
                "Compatibility, permissions and error responses verified.",
              state: "approved",
              stateLabel: "Approved",
              owner: "JV",
            },
            {
              id: "BLD-51",
              type: "QUALITY",
              title: "Keyboard reading of the form",
              detail: "Focus-order failure detected on the Documents step.",
              state: "blocked",
              stateLabel: "Blocks",
              owner: "SM",
            },
            {
              id: "BLD-55",
              type: "REVIEW",
              title: "Human approval of changes",
              detail: "Product reviews the scope before enabling the merge.",
              state: "queued",
              stateLabel: "Assigned",
              owner: "AG",
            },
          ],
          activity: [
            {
              initials: "JV",
              actor: "Juan V.",
              action: "approved the service contract",
              time: "14:08",
              state: "approved",
            },
            {
              initials: "QA",
              actor: "Quality assistant",
              action: "reported the keyboard block on BLD-51",
              time: "13:52",
              state: "blocked",
            },
            {
              initials: "MR",
              actor: "Mateo R.",
              action: "requested human review of the merge",
              time: "13:31",
              state: "review",
            },
          ],
          command: "inplux build run --quality-gates strict",
        },
        {
          code: "04",
          id: "RLS-09",
          title: "Release",
          status: "READY",
          statusTone: "ready",
          summary:
            "We ship with evidence, observability and a clear rollback path. Production is part of the product too.",
          progress: 96,
          boardLabel: "Release operation",
          boardNote: "Candidate 09 · approval on record",
          owner: "Laura Pérez",
          ownerInitials: "LP",
          gate: "Safe production",
          milestone: "Release / Jul 26",
          updated: "16:32 COT",
          metrics: [
            { label: "Gates", value: "08/08", detail: "approved" },
            { label: "Errors", value: "0.08%", detail: "last 30 min" },
            { label: "Response", value: "184ms", detail: "p95" },
          ],
          workItems: [
            {
              id: "RLS-09",
              type: "ARTIFACT",
              title: "Candidate 2026.07.26-rc.3",
              detail: "SHA 55c9d11 · signed image · SBOM attached.",
              state: "approved",
              stateLabel: "Signed",
              owner: "LP",
            },
            {
              id: "DEP-28",
              type: "DEPLOYMENT",
              title: "Production · BOG region",
              detail: "100% available · 3 healthy replicas.",
              state: "ready",
              stateLabel: "Healthy",
              owner: "MR",
            },
            {
              id: "OBS-14",
              type: "OBSERVABILITY",
              title: "SLO of the filing flow",
              detail: "99.96% availability · no regressions detected.",
              state: "active",
              stateLabel: "Live",
              owner: "JV",
            },
            {
              id: "RBK-03",
              type: "ROLLBACK",
              title: "Snapshot and procedure",
              detail: "Last rehearsal completed in 02:18.",
              state: "approved",
              stateLabel: "Verified",
              owner: "CE",
            },
          ],
          activity: [
            {
              initials: "CE",
              actor: "Cristian E.",
              action: "authorized the move to production",
              time: "16:32",
              state: "ready",
            },
            {
              initials: "LP",
              actor: "Laura P.",
              action: "signed artifact RLS-09",
              time: "16:21",
              state: "approved",
            },
            {
              initials: "MR",
              actor: "Mateo R.",
              action: "verified the rollback path",
              time: "15:48",
              state: "approved",
            },
          ],
          command: "inplux release --production --human-approved",
        },
      ],
    },
  },

  press: {
    eyebrow: "06 / PRESS AND CONVERSATIONS",
    titleLead: "The work also enters the ",
    titleEmphasis: "conversation.",
    archiveLink: "See the archive",
    storyLang: "es",
    storyNote:
      "Headlines keep their original Spanish; the summaries are ours, in English.",
    sourceAction: "Go to the source",
    externalLabel: "{title} — {outlet} (opens in a new tab)",
    categories: {
      Medios: "Media",
      "Escenarios públicos": "Public forums",
      Investigación: "Research",
      "Ideas firmadas": "Signed ideas",
    },
    formats: {
      Entrevista: "Interview",
      Prensa: "Press",
      "Selección editorial": "Editorial pick",
      Panel: "Panel",
      Preprint: "Preprint",
      "Working paper": "Working paper",
      "Columna firmada": "Signed column",
    },
    bylines: {
      "Curaduría editorial: The Commonplace":
        "Editorial curation: The Commonplace",
      "Entrevista a Jaime Alonso Cano Pino":
        "Interview with Jaime Alonso Cano Pino",
      "Nota sobre investigación de Cristian Espinal Maya y Santiago Jiménez Londoño":
        "Report on research by Cristian Espinal Maya and Santiago Jiménez Londoño",
    },
    editorialStatuses: {
      "Publicación del equipo · no es cobertura independiente":
        "Published by the team · not independent coverage",
      "Participación en panel · programa oficial del evento":
        "Panel participation · official event programme",
      "Selección editorial externa": "External editorial selection",
      "Publicada por Notas Al Poniente": "Published by Notas Al Poniente",
      "Working paper · no revisado por pares":
        "Working paper · not peer reviewed",
      "Preprint · no revisado por pares": "Preprint · not peer reviewed",
      "Nota editorial externa sobre investigación del equipo":
        "External editorial note about the team's research",
    },
    summaries: {
      "ia-arbitraje-congreso-cca":
        "Cristian Espinal took part in panel 11 of the 14th National and International Arbitration Congress, held in Medellín.",
      "commonplace-ia-trabajo":
        "Workforce Futures, an international newsletter, selected two of the team's papers on human capital and people-centred AI.",
      "tribai-cerebro-tributario":
        "A conversation about how Tribai started, the problem of looking for tax knowledge across scattered documents, and how the product was built.",
    },
    visualSignals: {
      "ia-arbitraje-congreso-cca": "14TH CONGRESS / MEDELLÍN",
      "commonplace-ia-trabajo": "WEEKLY RESEARCH DIGEST",
      "tribai-cerebro-tributario": "TRIBAI / INTERVIEW",
    },
    imageAlts: {
      "commonplace-ia-trabajo": "The Commonplace symbol",
      "tribai-cerebro-tributario":
        "Cover of the Tribai interview published by Al Poniente",
    },
    publishedLabels: {
      "ia-arbitraje-congreso-cca": "07 MAY 2026",
      "commonplace-ia-trabajo": "06 APR 2026",
      "tribai-cerebro-tributario": "24 MAR 2026",
    },
    markName: "THE COMMONPLACE",
    statCopy: "of formal employees choose the hours they work",
    statEyebrow: "Finding / Colombia",
    panelScenario: "Public forum",
    panelPlace: "Medellín / CO",
    panelLive: "LIVE",
    paperEyebrow: "INPLUX / RESEARCH",
    paperCode: "OPEN PAPER",
    paperFoot: "Read · compare · cite",
    archiveIdeas: "IDEAS",
  },

  contact: {
    eyebrow: "08 / THE NEXT PRODUCT",
    titleLead: "Let's build what ",
    titleEmphasis: "comes next.",
    lead: "Tell us the problem, who lives with it and what should change. You don't need to arrive with requirements or a defined scope.",
    entityStatement:
      "INPLUX LLC is a limited liability company with its office in Miami, Florida. From there we provide software services to clients abroad, with the engineering team of INPLUX S.A.S. in Medellín, Colombia.",
    cta: "Start a project",
    heroCtaAriaLabel: "Start a project",
    email: "gerencia@inplux.co",
    linkedInLabel: "LinkedIn ↗",
    locations: ["Miami, Florida · United States", "Medellín, Antioquia · Colombia"],
  },
};
