import { productNavigation, publicNavigation } from "@/content/navigation";
import type { HomeCopy } from "./types";

/**
 * Copy español de la HOME. Es la fuente de verdad de la ruta `/` y el valor
 * por defecto de todos los componentes de la home, así que cada cadena debe
 * coincidir literalmente con lo que la página publicaba antes de introducir
 * esta capa.
 */
export const homeCopyEs: HomeCopy = {
  locale: "es_CO",
  htmlLang: "es-CO",

  header: {
    skipToContent: "Saltar al contenido",
    brandLabel: "INPLUX, ir al inicio",
    navigationLabel: "Navegación principal",
    mobileNavigationLabel: "Navegación móvil",
    mobileMenuLabel: "Explora INPLUX",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
    contactCta: "Empezar un proyecto",
    contactCtaMobile: "Empezar un proyecto",
    menuNote: "No necesitas tener el alcance definido.",
    navigation: publicNavigation.map(([label, href]) => ({ label, href })),
    languageSwitch: null,
  },

  footer: {
    heading: "Pie de página",
    tagline: "Fábrica de software a la medida para empresas y entidades.",
    groups: [
      {
        label: "Explora",
        ariaLabel: "Explorar",
        items: publicNavigation.map(([label, href]) => ({ label, href })),
      },
      {
        label: "Productos",
        ariaLabel: "Productos documentados",
        items: productNavigation.map(([label, href]) => ({ label, href })),
      },
      {
        label: "Capacidades",
        ariaLabel: "Capacidades",
        items: [
          { label: "Producto digital", href: "/capacidades#producto" },
          { label: "Modernización", href: "/capacidades#modernizacion" },
          { label: "IA aplicada", href: "/capacidades#ia" },
          { label: "Servicios públicos", href: "/capacidades#sector-publico" },
        ],
      },
    ],
    contactLabel: "Contacto",
    contactAriaLabel: "Contacto",
    contactCta: "Empezar un proyecto",
    email: "gerencia@inplux.co",
    linkedInLabel: "LinkedIn",
    locations: ["Medellín, Colombia"],
    languageNote: null,
    copyright: "INPLUX S.A.S.",
    closingLine: "Software con criterio y dirección humana.",
  },

  contactDialog: {
    eyebrow: "Empecemos por el problema",
    titleLead: "¿Qué necesitas ",
    titleEmphasis: "construir",
    titleTail: "?",
    description:
      "Cuéntanos qué debería cambiar. No necesitas llegar con requisitos ni con el alcance definido.",
    closeLabel: "Cerrar formulario de contacto",
  },

  contactForm: {
    dialogLabel: "Formulario de contacto en diálogo",
    sectionLabel: "Formulario de contacto de la página",
    nameLabel: "Nombre",
    organizationLabel: "Empresa o entidad",
    organizationOptional: "opcional",
    needLabel: "¿Qué tipo de necesidad tienes?",
    needOptions: [
      "Lanzar un producto digital",
      "Mejorar una operación",
      "Automatizar trabajo y conocimiento",
      "Aún no lo sé",
    ],
    needDefault: "Aún no lo sé",
    challengeLabel: "¿Qué problema necesitas resolver?",
    challengePlaceholder:
      "Cuéntanos el problema, quién lo vive y qué debería cambiar.",
    note: "Prepararemos un borrador en tu aplicación de correo. Esta página no enviará ni almacenará los datos.",
    submit: "Abrir borrador en mi correo",
    preparedNote:
      "El borrador quedó preparado. Si tu aplicación de correo no se abrió, puedes copiar el mensaje y enviarlo desde el canal que prefieras.",
    copyAction: "Copiar mensaje preparado",
    copySuccess: "Mensaje copiado. Puedes pegarlo en el canal que prefieras.",
    copyFailure:
      "No pudimos copiarlo automáticamente. El mensaje está seleccionado abajo.",
    manualCopyLabel: "Mensaje preparado para copiar manualmente",
    mailSubject: "Nuevo reto de software · {organization}",
    mailFieldName: "Nombre",
    mailFieldOrganization: "Empresa o entidad",
    mailFieldOrganizationEmpty: "No indicada",
    mailFieldNeed: "Tipo de necesidad",
    mailChallengeHeading: "Reto:",
    mailTo: "Para",
    mailSubjectLabel: "Asunto",
  },

  hero: {
    eyebrow: "FÁBRICA DE SOFTWARE A LA MEDIDA",
    titleLines: ["De un problema real", "a software en producción."],
    leadSentences: [
      "INPLUX diseña, construye y evoluciona productos digitales para empresas y entidades.",
      "La IA acelera el trabajo. Personas expertas dirigen y validan las decisiones críticas.",
    ],
    primaryCta: "Empezar un proyecto",
    secondaryCta: "Ver trabajo real",
    statement: "EL SOFTWARE EMPIEZA EN EL PROBLEMA",
    signalAriaLabel: "Visual interactivo del flujo de una fábrica de software",
    signalMeta: [
      "ENTRADA / CONTEXTO",
      "MUEVE EL CURSOR PARA EXPLORAR",
      "SALIDA / PRODUCTO EN OPERACIÓN",
    ],
    signalStages: [
      { number: "01", title: "PROBLEMA REAL", detail: "PERSONAS + CONTEXTO" },
      { number: "02", title: "CONSTRUIR", detail: "DISEÑO + INGENIERÍA" },
      { number: "03", title: "EN PRODUCCIÓN", detail: "MEDIR + EVOLUCIONAR" },
    ],
    signalAxis: "BUILD / 01",
  },

  experienceRail: {
    ribbonAriaLabel: "Productos de INPLUX, cada uno con su fuente.",
    ribbonEyebrow: "PRODUCTOS / TRABAJO",
    ribbonTitle: "Lo que hemos construido.",
    directoryEyebrow: "EVIDENCIA / ATRIBUCIÓN",
    directoryName: "Directorio",
    directoryDetail: " productos documentados",
    logoWallAriaLabel: "Organizaciones con las que INPLUX ha trabajado.",
    statementEyebrow: "RELACIONES REALES",
    statementTitle: "EXPERIENCIA Y ALIANZAS",
    statementHint: "DESLIZA PARA VER 10 →",
    relationExperience: "Experiencia",
    relationPartner: "Aliado",
    clientNotes: {
      "/brand/clients/parque-arvi.png": "Turismo, territorio y sostenibilidad",
      "/brand/clients/think-it.png": "Aliado tecnológico",
      "/brand/clients/experience-03.png":
        "Gestión y servicios interinstitucionales",
      "/brand/clients/politecnico-jaime-isaza.png": "Educación superior pública",
      "/brand/clients/experience-04.png": "Cooperación territorial",
      "/brand/clients/experience-05.png": "Operación empresarial",
      "/brand/clients/experience-06-transparent.png": "Desarrollo urbano",
      "/brand/clients/experience-07.png": "Tecnología para la gestión pública",
      "/brand/clients/municipio-cisneros.png": "Gestión pública territorial",
      "/brand/clients/experience-08.png": "Gestión pública territorial",
    },
    productCategories: {},
    productStatuses: {},
  },

  factoryScrolly: {
    disclosure: "Demostración interactiva · datos ilustrativos",
    sceneDisclosure: "Demo / 04 etapas",
    eyebrow: "01 / LA FÁBRICA EN VIVO",
    titleLead: "Software construido para ",
    titleEmphasis: "evolucionar.",
    lead: "No ensamblamos pantallas aisladas. Construimos un sistema en el que contexto, producto e ingeniería avanzan juntos hasta poner software útil en operación.",
    timelineAriaLabel: "Etapas de la fábrica",
    introStatus: "Introducción a la fábrica",
    stageStatus: "Etapa {index} de {total}: {label}. {title}.",
    steps: [
      {
        index: "01",
        label: "TU RETO",
        title: "Entender",
        copy: "Observamos el contexto, escuchamos a las personas y hacemos visible el problema que realmente vale la pena resolver.",
        signals: ["PERSONAS / CONTEXTO", "REGLAS / FRICCIONES"],
      },
      {
        index: "02",
        label: "EL PRODUCTO",
        title: "Dar forma",
        copy: "Convertimos lo aprendido en prioridades, flujos y una experiencia que se puede probar antes de escalar.",
        signals: ["FLUJOS / DECISIONES", "INTERFAZ / PROTOTIPO"],
      },
      {
        index: "03",
        label: "LA FÁBRICA",
        title: "Construir",
        copy: "Diseño, ingeniería e inteligencia aplicada trabajan como un solo sistema, con revisión humana en cada punto crítico.",
        signals: ["DISEÑO / INGENIERÍA", "IA / REVISIÓN HUMANA"],
      },
      {
        index: "04",
        label: "EN PRODUCCIÓN",
        title: "Evolucionar",
        copy: "Lanzamos una versión útil, observamos cómo funciona y decidimos contigo qué mejorar a partir de evidencia real.",
        signals: ["DATOS / APRENDIZAJE", "OPERACIÓN / EVOLUCIÓN"],
      },
    ],
  },

  solutions: {
    eyebrow: "02 / QUÉ CONSTRUIMOS",
    titleLead: "Software para lo que tu organización necesita ",
    titleEmphasis: "hacer posible.",
    tabsAriaLabel: "Tipos de proyecto",
    disclosure: "DEMOSTRACIÓN INTERACTIVA · DATOS ILUSTRATIVOS",
    projectPrefix: "PROJECT",
    factoryLabel: "INPLUX FACTORY",
    toggleTitle: "Alternar entre la aplicación y la API",
    requestPaneLabel: "Solicitud API",
    responsePaneLabel: "Respuesta API",
    copyAction: "COPIAR",
    copyDone: "COPIADO",
    copyFailed: "NO FUE POSIBLE COPIAR",
    copyRequestLabel: "Copiar request del proyecto {project}",
    copyResponseLabel: "Copiar response del proyecto {project}",
    responseNotRun: "NOT RUN",
    responseRunning: "EXECUTING",
    responseIdleHint: "Ejecuta el request para inspeccionar la respuesta.",
    responseRunningHint: "Validando contrato y permisos…",
    runRequest: "RUN REQUEST",
    runAgain: "RUN AGAIN",
    running: "RUNNING…",
    sandboxReady: "SANDBOX READY",
    validatingContract: "VALIDANDO CONTRATO",
    responseReady: "RESPONSE READY",
    workbenchLabel: "API WORKBENCH",
    projectFieldLabel: "PROYECTO",
    ownerFieldLabel: "RESPONSABLE",
    stateFieldLabel: "ESTADO",
    projectIdFieldLabel: "PROJECT ID",
    environmentFieldLabel: "ENTORNO",
    updatedFieldLabel: "ACTUALIZADO",
    appNavigation: ["RESUMEN", "ACTIVIDAD", "EVIDENCIA"],
    ownerAriaLabel: "Responsable: {owner}",
    recentActivityLabel: "ACTIVIDAD RECIENTE",
    outcomeLabel: "RESULTADO",
    items: [
      {
        number: "01",
        title: "Lanzar un producto digital",
        copy: "Convertimos una oportunidad en una primera versión útil, preparada para aprender y crecer.",
        status: "PRODUCT DISCOVERY",
        outcome: "Primera versión lista para validar",
        modules: ["Contexto", "Experiencia", "Producto", "Entrega"],
        image: "/brand/home/solution-product.webp",
        imagePosition: "50% 50%",
        project: {
          id: "PRJ-0718",
          name: "Órbita piloto",
          owner: "Laura M.",
          ownerInitials: "LM",
          state: "Lista para validar",
          environment: "PILOTO",
          updated: "Hace 12 min",
        },
        ui: {
          kind: "release",
          eyebrow: "PRODUCT RELEASE / 01",
          value: "V1.0",
          description: "Primera versión preparada para validar.",
          metrics: [
            ["USUARIOS PILOTO", "48"],
            ["FLUJOS CLAVE", "06"],
            ["COBERTURA", "82%"],
            ["RIESGO", "BAJO"],
          ],
          progress: 82,
          progressLabel: "Cobertura de validación",
          activity: [
            ["Onboarding", "VALIDADO"],
            ["Flujo principal", "READY"],
          ],
          artifact: {
            stages: ["DISCOVERY", "PROTOTYPE", "PILOT", "RELEASE"],
            cohortLabel: "COHORTE PILOTO",
            cohortValue: "48 PERSONAS · 06 FLUJOS",
          },
        },
        api: {
          method: "POST",
          endpoint: "/v1/projects/PRJ-0718/releases",
          action: "publish_pilot_release",
          httpStatus: "201 CREATED",
          latency: "86 ms",
        },
      },
      {
        number: "02",
        title: "Modernizar una operación",
        copy: "Conectamos personas, procesos, reglas y datos alrededor de la forma real de trabajar.",
        status: "OPERATION DESIGN",
        outcome: "Operación conectada y trazable",
        modules: ["Personas", "Procesos", "Reglas", "Datos"],
        image: "/brand/home/solution-operation.webp",
        imagePosition: "50% 52%",
        project: {
          id: "OPS-1842",
          name: "Flujo de casos",
          owner: "Santiago R.",
          ownerInitials: "SR",
          state: "En ejecución",
          environment: "PRODUCCIÓN",
          updated: "Hace 4 min",
        },
        ui: {
          kind: "operation",
          eyebrow: "CASE FLOW / 1842",
          value: "12m",
          description: "Tiempo medio para resolver un caso.",
          metrics: [
            ["CASOS ACTIVOS", "186"],
            ["PASOS", "04"],
            ["SLA", "94%"],
            ["REPROCESO", "−31%"],
          ],
          progress: 74,
          progressLabel: "Flujo completado",
          activity: [
            ["Validación de regla", "PASS"],
            ["Asignación automática", "DONE"],
          ],
          artifact: {
            queues: [
              ["ENTRADA", "186"],
              ["VALIDACIÓN", "42"],
              ["REVISIÓN", "18"],
              ["RESUELTOS", "126"],
            ],
          },
        },
        api: {
          method: "POST",
          endpoint: "/v1/projects/OPS-1842/cases/1842/advance",
          action: "advance_to_human_review",
          httpStatus: "200 OK",
          latency: "112 ms",
        },
      },
      {
        number: "03",
        title: "Activar conocimiento con IA",
        copy: "Convertimos tareas repetitivas y conocimiento disperso en flujos claros, con control humano.",
        status: "KNOWLEDGE SYSTEM",
        outcome: "Conocimiento disponible al decidir",
        modules: ["Fuentes", "Criterios", "Flujos", "Revisión"],
        image: "/brand/home/solution-knowledge.webp",
        imagePosition: "50% 45%",
        project: {
          id: "KNO-0031",
          name: "Criterio asistido",
          owner: "María P.",
          ownerInitials: "MP",
          state: "Revisión aprobada",
          environment: "CONTROLADO",
          updated: "Hace 7 min",
        },
        ui: {
          kind: "knowledge",
          eyebrow: "KNOWLEDGE QUERY / 031",
          value: "94%",
          description: "Confianza de la respuesta con evidencia.",
          metrics: [
            ["FUENTES", "04"],
            ["CITAS", "07"],
            ["REVISIÓN", "HUMANA"],
            ["COLA", "00"],
          ],
          progress: 94,
          progressLabel: "Confianza verificada",
          activity: [
            ["Política interna", "CITADA"],
            ["Criterio experto", "APROBADO"],
          ],
          artifact: {
            statement:
              "La decisión aplica cuando existe evidencia verificable y una persona responsable confirma el criterio.",
            chips: ["FUENTE 01", "FUENTE 02", "CRITERIO EXPERTO"],
            chipVerdict: "REVISADO",
          },
        },
        api: {
          method: "POST",
          endpoint: "/v1/projects/KNO-0031/knowledge/query",
          action: "answer_with_verified_sources",
          httpStatus: "200 OK",
          latency: "148 ms",
        },
      },
      {
        number: "04",
        title: "Evolucionar un servicio público",
        copy: "Diseñamos experiencias claras para ciudadanía y equipos internos, con seguimiento de punta a punta.",
        status: "PUBLIC SERVICE",
        outcome: "Servicio visible, conectado y medible",
        modules: ["Ciudadanía", "Trámite", "Seguimiento", "Control"],
        image: "/brand/home/solution-public-service.webp",
        imagePosition: "50% 52%",
        project: {
          id: "GOV-0184",
          name: "Trámite conectado",
          owner: "Ana C.",
          ownerInitials: "AC",
          state: "En revisión técnica",
          environment: "SERVICIO",
          updated: "Hace 9 min",
        },
        ui: {
          kind: "service",
          eyebrow: "TRÁMITE / 2026-0184",
          value: "03 / 04",
          description: "Etapa actual visible para ciudadanía y equipo.",
          metrics: [
            ["SOLICITUDES", "284"],
            ["TIEMPO MEDIO", "2.4D"],
            ["TRAZABILIDAD", "100%"],
            ["ALERTAS", "02"],
          ],
          progress: 75,
          progressLabel: "Progreso del trámite",
          activity: [
            ["Documento recibido", "VERIFICADO"],
            ["Revisión técnica", "EN CURSO"],
          ],
          artifact: {
            steps: [
              ["01", "SOLICITUD", "DONE"],
              ["02", "DOCUMENTOS", "DONE"],
              ["03", "REVISIÓN TÉCNICA", "ACTIVE"],
              ["04", "RESPUESTA", "NEXT"],
            ],
          },
        },
        api: {
          method: "GET",
          endpoint: "/v1/projects/GOV-0184/procedures/2026-0184",
          action: "read_procedure_status",
          httpStatus: "200 OK",
          latency: "96 ms",
        },
      },
    ],
  },

  apiChapter: {
    eyebrow: "03 / INTEGRACIÓN",
    titleLead: "Listo para integrarse.",
    titleTail: "Hecho para ",
    titleEmphasis: "evolucionar.",
    lead: "Construimos software que conversa con lo que tu organización ya usa y deja una base clara para lo que vendrá después.",
    capabilities: [
      [
        "Interfaces y APIs claras",
        "Cada integración tiene un contrato comprensible y verificable.",
      ],
      [
        "Seguridad desde el diseño",
        "Identidad, permisos y trazabilidad se definen desde el principio.",
      ],
      [
        "Integraciones observables",
        "Sabemos qué ocurrió, cuándo y por qué, sin depender de cajas negras.",
      ],
      [
        "Documentación viva",
        "El producto y su documentación evolucionan como una sola pieza.",
      ],
    ],
    primaryCta: "Hablemos de tu arquitectura",
    secondaryCta: "Ver la fábrica",
    demoAriaLabel: "Demostración para crear un proyecto en INPLUX Factory",
    demoDisclosure: "DEMOSTRACIÓN INTERACTIVA · DATOS ILUSTRATIVOS",
    createProjectComment: "// CREATE PROJECT",
    environmentLabel: "ENV / SANDBOX",
    regionLabel: "REGION / LATAM-01",
    copyEndpoint: "Copiar endpoint",
    copiedEndpoint: "Endpoint copiado",
    copiedTitle: "Copiado",
    copyEndpointAnnouncement: "Endpoint copiado al portapapeles.",
    copyEndpointFailure: "No fue posible copiar el endpoint.",
    sandboxReady: "SANDBOX READY",
    creatingProject: "CREATING PROJECT…",
    projectCreated: "PROJECT CREATED",
    runRequest: "RUN REQUEST",
    running: "RUNNING",
    runAgain: "RUN AGAIN",
    responseReadyLabel: "READY",
    responseCreatedLabel: "201 / CREATED",
    responseFields: [
      ["PROJECT", "IX-0718"],
      ["NEXT GATE", "CONTEXT / 01"],
      ["TRACE", "ENABLED"],
    ],
    openInFactoryRun: "ABRIR IX-0718 EN FACTORY RUN",
  },

  sectors: {
    eyebrow: "04 / DÓNDE TRABAJAMOS",
    title: "Dos contextos. Un mismo estándar de producto.",
    publicEyebrow: "SECTOR PÚBLICO / 01",
    publicTitle: "Servicios que sostienen lo colectivo.",
    publicCopy:
      "Digitalizamos atención, información y seguimiento para que la operación sea más clara, conectada y trazable.",
    publicItems: [
      "Atención y trámites",
      "Gestión y seguimiento",
      "Datos para decidir",
    ],
    publicCta: "Hablemos de un reto público",
    privateEyebrow: "SECTOR PRIVADO / 02",
    privateTitle: "Productos que mueven el negocio.",
    privateCopy:
      "Construimos productos y herramientas internas que convierten procesos, conocimiento y datos en una operación que puede crecer.",
    privateItems: [
      "Productos digitales",
      "Operaciones internas",
      "Automatización con control",
    ],
    privateCta: "Hablemos de un reto privado",
  },

  build: {
    eyebrow: "05 / CÓMO TRABAJAMOS",
    title: "Una fábrica diseñada para entregar.",
    lead: "La tecnología cambia rápido. Nuestro sistema de trabajo está diseñado para aprender sin perder claridad, responsabilidad ni control.",
    deliveryChecks: [
      [
        "Problema y resultado primero",
        "Alineamos propósito, personas y evidencia antes de definir el alcance.",
      ],
      [
        "Diseño e ingeniería juntos",
        "Una sola mesa de trabajo reduce traducciones y decisiones tardías.",
      ],
      [
        "Demostraciones frecuentes",
        "Ves software funcionando y decides con algo concreto frente a ti.",
      ],
      [
        "Inteligencia con supervisión",
        "La IA acelera el trabajo; el criterio humano conserva la dirección.",
      ],
      [
        "Medición en producción",
        "Cada versión genera señales para decidir qué conviene evolucionar.",
      ],
    ],
    primaryCta: "Empezar un proyecto",
    secondaryCta: "Ver la fábrica",
    capabilitiesEyebrow: "06 / HECHA PARA AVANZAR",
    capabilitiesTitle: "Ritmo de entrega, sin perder criterio ni control.",
    capabilities: [
      [
        "01",
        "Propósito antes que alcance",
        "Partimos del problema y del resultado esperado, no de una lista cerrada de pantallas.",
      ],
      [
        "02",
        "Una sola mesa de trabajo",
        "Contexto, diseño e ingeniería deciden juntos para reducir pérdida de información.",
      ],
      [
        "03",
        "Inteligencia con supervisión",
        "Sistemas de IA aceleran investigación, código y pruebas; las decisiones siguen bajo dirección humana.",
      ],
      [
        "04",
        "Evidencia para evolucionar",
        "Cada versión en uso produce señales que orientan la siguiente decisión de producto.",
      ],
    ],
    factoryRun: {
      regionAriaLabel:
        "Factory Run de INPLUX. Selecciona una fase para inspeccionar su ejecución.",
      demoFlag: "DEMOSTRACIÓN INTERACTIVA",
      demoFlagDetail: "DATOS ILUSTRATIVOS",
      runLabel: "RUN IX-0718",
      runOwnerAriaLabel: "Responsable Cristian Espinal",
      railAriaLabel: "Navegación de Factory Run",
      projectLabel: "PROYECTO",
      projectName: "Portal de licencias",
      projectMeta: "IX-0718 · EN EJECUCIÓN",
      phasesLabel: "FASES DE ENTREGA",
      phaseTabsAriaLabel: "Fases de la fábrica",
      runActive: "RUN ACTIVO",
      breadcrumbProject: "Proyecto",
      breadcrumbPhase: "Fase",
      scrollableDetailAriaLabel: "Detalle desplazable de la fase {phase}",
      inspectorAriaLabel: "Inspector de {phase}",
      phasePrefix: "INPLUX FACTORY · FASE",
      ownerLabel: "RESPONSABLE",
      gateProgressAriaLabel: "Avance del gate {gate}",
      gateLabel: "GATE",
      boardPriorities: "3 PRIORIDADES VISIBLES",
      propertiesTitle: "Propiedades",
      gateFieldLabel: "Gate",
      milestoneFieldLabel: "Milestone",
      updatedFieldLabel: "Actualizado",
      activityTitle: "Actividad",
      activityCount: "2 RECIENTES",
      authorityLabel: "DIRECCIÓN",
      authorityNote: "La IA propone y ejecuta. Una persona conserva la decisión.",
      scrollCue: "DESLIZA PARA MÁS DETALLE",
      runApiLabel: "RUN API",
      syncedLabel: "DATOS SINCRONIZADOS",
      announcement: "Fase activa: {phase}. Estado {status}.",
      phases: [
        {
          code: "01",
          id: "CTX-07",
          title: "Contexto",
          status: "ALINEADO",
          statusTone: "approved",
          summary:
            "Unimos conversaciones, restricciones y evidencia para que el resultado tenga una definición compartida.",
          progress: 84,
          boardLabel: "Evidencia del contexto",
          boardNote: "4 elementos · 1 requiere decisión",
          owner: "Cristian Espinal",
          ownerInitials: "CE",
          gate: "Resultado compartido",
          milestone: "Definición / 19 jul",
          updated: "09:12 COT",
          metrics: [
            { label: "Actores", value: "12", detail: "mapeados" },
            { label: "Reglas", value: "18", detail: "trazadas" },
            { label: "Fricciones", value: "06", detail: "priorizadas" },
          ],
          workItems: [
            {
              id: "CTX-12",
              type: "BRIEF",
              title: "Resultado que debe cambiar",
              detail:
                "Reducir de 11 a 4 días el alta de una solicitud completa.",
              state: "approved",
              stateLabel: "Aprobado",
              owner: "CE",
            },
            {
              id: "CTX-15",
              type: "PERSONAS",
              title: "Mapa de actores y autoridad",
              detail:
                "Ciudadanía, revisión técnica y aprobación jurídica conectadas.",
              state: "approved",
              stateLabel: "Trazado",
              owner: "ME",
            },
            {
              id: "CTX-18",
              type: "FRICCIÓN",
              title: "Validación de identidad",
              detail:
                "Definir excepción para documentos con lectura incompleta.",
              state: "review",
              stateLabel: "Revisión",
              owner: "LP",
            },
            {
              id: "CTX-21",
              type: "EVIDENCIA",
              title: "Umbral de éxito",
              detail:
                "80% completa el flujo sin asistencia en la primera sesión.",
              state: "ready",
              stateLabel: "Listo",
              owner: "AG",
            },
          ],
          activity: [
            {
              initials: "ME",
              actor: "María E.",
              action: "conectó 3 reglas al flujo de validación",
              time: "08:58",
              state: "approved",
            },
            {
              initials: "LP",
              actor: "Laura P.",
              action: "solicitó criterio jurídico en CTX-18",
              time: "08:41",
              state: "review",
            },
            {
              initials: "CE",
              actor: "Cristian E.",
              action: "fijó el resultado y su umbral",
              time: "Ayer",
              state: "ready",
            },
          ],
          command: "inplux context lock --outcome service-adoption",
        },
        {
          code: "02",
          id: "PRD-18",
          title: "Producto",
          status: "VALIDANDO",
          statusTone: "active",
          summary:
            "Hacemos visible la solución antes de construirla: flujos, decisiones y prototipos que las personas pueden probar.",
          progress: 68,
          boardLabel: "Plan de producto",
          boardNote: "4 historias · sesión 03 en curso",
          owner: "Ana Gómez",
          ownerInitials: "AG",
          gate: "Flujo comprensible",
          milestone: "Prototipo / 22 jul",
          updated: "11:46 COT",
          metrics: [
            { label: "Flujos", value: "04", detail: "modelados" },
            { label: "Pruebas", value: "09", detail: "completadas" },
            { label: "Claridad", value: "8.7", detail: "sobre 10" },
          ],
          workItems: [
            {
              id: "PRD-31",
              type: "FLUJO",
              title: "Radicar una solicitud",
              detail:
                "Ingreso, validación y confirmación en un recorrido único.",
              state: "approved",
              stateLabel: "Validado",
              owner: "AG",
            },
            {
              id: "PRD-34",
              type: "PROTOTIPO",
              title: "Bandeja de seguimiento",
              detail:
                "Estado, próximos pasos y evidencia visible para cada caso.",
              state: "active",
              stateLabel: "Probando",
              owner: "SM",
            },
            {
              id: "PRD-37",
              type: "DECISIÓN",
              title: "Recuperación de una solicitud",
              detail:
                "Dos alternativas abiertas después de pruebas con 5 personas.",
              state: "review",
              stateLabel: "Decidir",
              owner: "CE",
            },
            {
              id: "PRD-40",
              type: "CONTENIDO",
              title: "Mensajes de validación",
              detail:
                "Lenguaje claro revisado; pendiente control de accesibilidad.",
              state: "queued",
              stateLabel: "En cola",
              owner: "LP",
            },
          ],
          activity: [
            {
              initials: "SM",
              actor: "Santiago M.",
              action: "publicó el prototipo 0.8",
              time: "11:46",
              state: "active",
            },
            {
              initials: "AG",
              actor: "Ana G.",
              action: "cerró 3 hallazgos de usabilidad",
              time: "10:22",
              state: "approved",
            },
            {
              initials: "CE",
              actor: "Cristian E.",
              action: "agendó decisión para PRD-37",
              time: "09:54",
              state: "review",
            },
          ],
          command: "inplux prototype test --flow citizen-onboarding",
        },
        {
          code: "03",
          id: "BLD-42",
          title: "Build",
          status: "EN ENSAMBLE",
          statusTone: "active",
          summary:
            "Diseño e ingeniería trabajan sobre el mismo sistema, con agentes especializados y revisión humana en cada gate.",
          progress: 57,
          boardLabel: "Cambios en integración",
          boardNote: "3 cambios · CI ejecutando",
          owner: "Mateo Ríos",
          ownerInitials: "MR",
          gate: "Calidad verificable",
          milestone: "Candidate / 25 jul",
          updated: "14:08 COT",
          metrics: [
            { label: "Cambios", value: "38", detail: "integrados" },
            { label: "Cobertura", value: "92%", detail: "rutas críticas" },
            { label: "Agentes", value: "04", detail: "supervisados" },
          ],
          workItems: [
            {
              id: "PR-184",
              type: "MERGE REQUEST",
              title: "feat/intake-validation",
              detail: "17 archivos · +426 −118 · commit a91e2f7",
              state: "active",
              stateLabel: "CI 7/9",
              owner: "MR",
            },
            {
              id: "BLD-46",
              type: "CONTRATO",
              title: "Schema de radicación v3",
              detail:
                "Compatibilidad, permisos y respuestas de error verificadas.",
              state: "approved",
              stateLabel: "Aprobado",
              owner: "JV",
            },
            {
              id: "BLD-51",
              type: "CALIDAD",
              title: "Lectura por teclado del formulario",
              detail:
                "Falla de orden de foco detectada en el paso Documentos.",
              state: "blocked",
              stateLabel: "Bloquea",
              owner: "SM",
            },
            {
              id: "BLD-55",
              type: "REVISIÓN",
              title: "Aprobación humana de cambios",
              detail: "Producto revisa alcance antes de habilitar el merge.",
              state: "queued",
              stateLabel: "Asignado",
              owner: "AG",
            },
          ],
          activity: [
            {
              initials: "JV",
              actor: "Juan V.",
              action: "aprobó el contrato de servicio",
              time: "14:08",
              state: "approved",
            },
            {
              initials: "QA",
              actor: "Quality agent",
              action: "reportó bloqueo de teclado en BLD-51",
              time: "13:52",
              state: "blocked",
            },
            {
              initials: "MR",
              actor: "Mateo R.",
              action: "solicitó revisión humana del merge",
              time: "13:31",
              state: "review",
            },
          ],
          command: "inplux build run --quality-gates strict",
        },
        {
          code: "04",
          id: "RLS-09",
          title: "Release",
          status: "LISTO",
          statusTone: "ready",
          summary:
            "Publicamos con evidencia, observabilidad y una ruta de reversión clara. Producción también es parte del producto.",
          progress: 96,
          boardLabel: "Operación del release",
          boardNote: "Candidate 09 · aprobación registrada",
          owner: "Laura Pérez",
          ownerInitials: "LP",
          gate: "Producción segura",
          milestone: "Release / 26 jul",
          updated: "16:32 COT",
          metrics: [
            { label: "Gates", value: "08/08", detail: "aprobados" },
            { label: "Errores", value: "0.08%", detail: "últimos 30 min" },
            { label: "Respuesta", value: "184ms", detail: "p95" },
          ],
          workItems: [
            {
              id: "RLS-09",
              type: "ARTEFACTO",
              title: "Candidate 2026.07.26-rc.3",
              detail: "SHA 55c9d11 · imagen firmada · SBOM adjunto.",
              state: "approved",
              stateLabel: "Firmado",
              owner: "LP",
            },
            {
              id: "DEP-28",
              type: "DESPLIEGUE",
              title: "Producción · región BOG",
              detail: "100% disponible · 3 réplicas saludables.",
              state: "ready",
              stateLabel: "Saludable",
              owner: "MR",
            },
            {
              id: "OBS-14",
              type: "OBSERVABILIDAD",
              title: "SLO del flujo de radicación",
              detail: "99.96% disponibilidad · sin regresiones detectadas.",
              state: "active",
              stateLabel: "En vivo",
              owner: "JV",
            },
            {
              id: "RBK-03",
              type: "REVERSIÓN",
              title: "Snapshot y procedimiento",
              detail: "Último ensayo completado en 02:18.",
              state: "approved",
              stateLabel: "Verificado",
              owner: "CE",
            },
          ],
          activity: [
            {
              initials: "CE",
              actor: "Cristian E.",
              action: "autorizó el paso a producción",
              time: "16:32",
              state: "ready",
            },
            {
              initials: "LP",
              actor: "Laura P.",
              action: "firmó el artefacto RLS-09",
              time: "16:21",
              state: "approved",
            },
            {
              initials: "MR",
              actor: "Mateo R.",
              action: "verificó la ruta de reversión",
              time: "15:48",
              state: "approved",
            },
          ],
          command: "inplux release --production --human-approved",
        },
      ],
    },
  },

  press: {
    eyebrow: "06 / PRENSA Y CONVERSACIONES",
    titleLead: "El trabajo también entra en ",
    titleEmphasis: "conversación.",
    archiveLink: "Ver el archivo",
    storyLang: null,
    storyNote: null,
    sourceAction: "Consultar fuente",
    externalLabel: "{title} — {outlet} (abre en una pestaña nueva)",
    categories: {},
    formats: {},
    bylines: {},
    editorialStatuses: {},
    summaries: {},
    visualSignals: {},
    imageAlts: {},
    publishedLabels: {},
    markName: "THE COMMONPLACE",
    statCopy: "empleados formales deciden a qué hora trabajan",
    statEyebrow: "Hallazgo / Colombia",
    panelScenario: "Escenario público",
    panelPlace: "Medellín / CO",
    panelLive: "EN VIVO",
    paperEyebrow: "INPLUX / RESEARCH",
    paperCode: "OPEN PAPER",
    paperFoot: "Leer · contrastar · citar",
    archiveIdeas: "IDEAS",
  },

  contact: {
    eyebrow: "08 / EL SIGUIENTE PRODUCTO",
    titleLead: "Construyamos lo que ",
    titleEmphasis: "sigue.",
    lead: "Cuéntanos el problema, quién lo vive y qué debería cambiar. No necesitas tener los requisitos ni el alcance definidos.",
    entityStatement: null,
    cta: "Empezar un proyecto",
    heroCtaAriaLabel: "Empezar un proyecto",
    email: "gerencia@inplux.co",
    linkedInLabel: "LinkedIn ↗",
    locations: ["Medellín, Antioquia · Colombia"],
  },
};
